language: python
python:
  - "3.6"
install:
  - pip install masonite-cli
  - pip install -r requirements_pipenv.txt
  - craft install
script: python -m pytest
notifications:
  slack: theoraclenetwork:gi7xHLDg5L74Lvs2XUxsq8eJ