name: Deploy Website

on:
  push:
    branches:
    - feature/hugo
  
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Hugo
        run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD} hugo
          mv hugo $HOME/hugo
        env:
          HUGO_VERSION: 0.73.0
      - name: Hugo Version
        run: $HOME/hugo version
      - name: Build Directory
        run: cd src
      - name: Look around
        run: ls -l
      - name: Hugo Build
        run: $HOME/hugo --minify --themesDir ../themes
      - name: Deploy to S3
        run: $HOME/hugo -v deploy  --themesDir ../themes --maxDeletes -1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
